### ISSUE TITLE
Better views of objects in the change list?

### ISSUE THREAD

**Issue by puterleat** [dominno/django-moderation#123]
I was trying to work out how to show more fields from the moderated content in the moderated object change_list view, i.e. /admin/moderation/moderatedobject/

It occurred that rather than simply allowing fields from the content object to be shown in columns, which might get messy, it might be better to allow for a single property/method on the moderated thing which (perhaps called `moderator_preview`) which, if present and callable, is added as a column in to the django change list (replacing the **repr** which is currently the first column).

**Comment by mpyatishev** [comment]
I'm using that method:
```
# admin.py
....
class ModeratedSomeModelManager(models.Manager):
    def get_queryset(self):
        return super(ModeratedSomeModelManager, self).get_queryset()\
            .filter(content_type=ContentType.objects.get_for_model(SomeModel))

class ModeratedSomeModel(ModeratedObject):
    class Meta:
        proxy = True
    objects = ModeratedSomeModelManager()

class ModeratedSomeModelAdmin(ModeratedObjectAdmin):
    list_display = ModeratedObjectAdmin.list_display + ('some_other_field',)
    change_form_template = 'somemodel/moderation/custom_template.html'

admin.site.register(ModeratedSomeModel, ModeratedSomeModelAdmin)
```
