### ISSUE TITLE
Problem with utf-8 characters

### ISSUE THREAD

**Issue by rmartins90** [dominno/django-moderation#124]
If there's some special characters on moderated objects, moderation throws an exception:
`'ascii' codec can't encode character ...`

solved it with following changes on diff.py:

```
value1, value2 = change
if value1 and (type(value1) is str or type(value1) is unicode):
  value1 = value1.encode('utf-8')
if value2 and (type(value2) is str or type(value2) is unicode):
  value2 = value2.encode('utf-8')
```

**Comment by DmytroLitvinov** [comment]
It was fixed in commit https://github.com/dominno/django-moderation/commit/f18ebd7bfaf1f846404e28ade6b2ac836453a46f
