### ISSUE TITLE
You don't have permission to edit anything (as a superuser)

### ISSUE THREAD

**Issue by ursomniac** [dominno/django-moderation#131]
I've installed this three times now, just to make sure I didn't goof up anywhere, but I cannot get the simplest case test scenario to work for me.  

All I've done it create a single simple model (Event) with the simplest field (title, date).  Database seems fine, auth.User settings (is_superuser=1) is right.  But as soon as I turn on moderation and go into the admin, I can't access a single record on any model.  "You don't have permission to edit anything."  

Looking at syncdb output it appears that moderation never properly migrates (it's always under "Not synced" even after applying migrations), and any app-level models ALSO now appear under there, and likewise will not sync.

Is there a missing step or steps in the docs?

**Comment by ursomniac** [comment]
4th time was the charm?

**Comment by dominno** [comment]
@ursomniac There was django 1.7 support merged recently, maybe that fixed that

**Comment by ursomniac** [comment]
I'm using Django 1.7 but I might be one rev behind?

In terms of meeting my upcoming project's need you had to have been hiding under the conference table.  This will save me WEEKS of work.  I can't thank you enough.

Bob Donahue
WGBH digital
