### ISSUE TITLE
Including user object on the moderate object

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [dominno/django-moderation#145]
Content object, Content type, Date created, Moderation status, Moderated by, Moderation date

These are the fields that are currently present on django-moderation. Wouldn't it be useful if it would be has the option to be with a User Foreign Key. So the moderator would know who tried to create the object?

**Comment by dominno** [comment]
Yes that would good thing, you can create PR and I will review it

**Comment by dominno** [comment]
@Dean-Christian-Armada There is already field called _changed_by_ so you can use that.
