### ISSUE TITLE
Doesn't work with models with UUIDs as primary keys

### ISSUE THREAD

**Issue by blag** [dominno/django-moderation#153]
The `ModeratedObject` model uses a `PositiveIntegerField` as the `object_pk` part of the GFK to the moderated object. That doesn't work if the PK of the moderated model is a `UUIDField`.

Some StackOverflow issues fix this by changing the `object_pk` field to a `CharField`, but this only works on "weakly typed" databases like MySQL. And I'm using...PostgreSQL, for which that doesn't work.

Unfortunately I don't really know of a good workaround at this point, I just wanted to point it out to other potential users. Besides this issue (and the lack of Django 1.10 support I've been unable to fix), django-moderation is a really good, high quality project. Thanks for all of your work!

**Comment by blag** [comment]
The [django-activity-stream](https://github.com/justquick/django-activity-stream) project may have run into a similar issue and solved it by making their `object_id` fields `CharField`, so they can also support non-integer primary keys. I don't know if it works for UUIDs on Postgres, but it sounds like at least [one guy](https://github.com/justquick/django-activity-stream/pull/309) got it working.

**Comment by zbyte64** [comment]
Rather common problem with django's generic foreign key. I believe Django taggit ships with alternative models for handling uuid fields.

**Comment by blag** [comment]
@zbyte64 Thanks for pointing me to Taggit - I'll check that out.

**Comment by blag** [comment]
I'm trying to work on this, and I think I *might* be able to get something to work reasonably efficiently. I'll be using django-polymorphic's `PolymorphicModel`. It may not be completely backwards compatible with previous versions, but I can get it to be close.

Will update when I have things working.

**Comment by DmytroLitvinov** [comment]
Closed because of inactivity.

We could add some useful note to README/docs something like we have [known issues](https://github.com/dominno/django-moderation#known-issues).
