### ISSUE TITLE
Coexist django-guardian with django-moderation?

### ISSUE THREAD

**Issue by Allan-Nava** [dominno/django-moderation#161]
Hi,

can coexist [django-guardian](https://github.com/django-guardian/django-guardian) and django-moderation in admin panel?

I need to handle an user's feed and activity with other user who have  the privilege.

Thank's for support

**Comment by DmytroLitvinov** [comment]
Hi,

It is not tested, so if you tested it and have some thoughts on it, feel free to write about it here that other users could find this issue.
