### ISSUE TITLE
[Question] Support for 2.0 ?

### ISSUE THREAD

**Issue by bukowa** [dominno/django-moderation#164]
Hello, i never used the app, but i wonder what is needed for 2.0 to work?

**Comment by MajorClod** [comment]
+1 - went to test this out for a current project using 2.0, however there are numerous issues preventing it from working out of the box.

**Comment by DmytroLitvinov** [comment]
Need to close it @dominno

**Comment by dominno** [comment]
Fixed in https://github.com/dominno/django-moderation/pull/178
