### ISSUE TITLE
inherited fields not getting moderated

### ISSUE THREAD

**Issue by zypro** [dominno/django-moderation#170]
I have a class which extends a class from a 3rd party package (named django-scheduler).

    from schedule.models import Event
    from moderation.db import ModeratedModel
    
    class Event(Event, ModeratedModel):
        more_fields = models.TextField()
        ...

The problem is now, that in the django Admin only the fields of my own Event class are getting "moderated". The inherited fields of the Event class from the scheduler package are shown in the admin too, but not being tracked/moderated... The diff isn't displayed.

Is it possible to tell the ModeratedModel class also to track the diff of the "foreign" Event fields?

**Comment by DmytroLitvinov** [comment]
HI @zypro ,

Would you mind confirming that you still have issue in new version of `django-moderation`?

**Comment by zypro** [comment]
Sorry @DmytroLitvinov , because of this bug I wrote my own Event class. So I can't confirm anything...
