### ISSUE TITLE
is_auto_approve not being called

### ISSUE THREAD

**Issue by bschelling** [dominno/django-moderation#176]
Python 3.6.8 and django-moderation 0.5.0.
I'm using moderation on the cms page model. Basic moderation works - but I don't want to moderate the creation of new pages, only the publishing of existing ones. 
I'm trying to achieve this by overriding is_auto_approve but the method never gets called.
I'm pretty much just starting on django so any input would be highly appreciated :)

```python
from moderation import moderation
from moderation.db import ModeratedModel
from moderation.moderator import GenericModerator
from cms.models import Page

class PageModerator(GenericModerator):
    def is_auto_approve(self, obj, user):
        #...check - no moderation for page creation only for publishing 
        super(PageModerator, self).is_auto_approve(obj, user)

moderation.register(Page, PageModerator)
```

**Comment by DmytroLitvinov** [comment]
We have released new version 0.7.0.
Reopen it if this error exists.
