### ISSUE TITLE
Update docs at readthedocs.io

### ISSUE THREAD

**Issue by DmytroLitvinov** [dominno/django-moderation#179]
Hi @dominno .
Could you please build latest changes from 0.7.0 version on https://django-moderation.readthedocs.io/en/stable/index.html?

**Comment by dominno** [comment]
Yes will do it at the weekend

**Comment by DmytroLitvinov** [comment]
@dominno friendly ping

**Comment by dominno** [comment]
@DmytroLitvinov done, also added you as Maintainer on readthedocs, so you can also build
