### ISSUE TITLE
Get rid of `django-model-utils` library

### ISSUE THREAD

**Issue by DmytroLitvinov** [dominno/django-moderation#187]
Currently, we are using `django-model-utils` library just for [Choices utility](https://django-model-utils.readthedocs.io/en/latest/utilities.html#choices).
I am proposing to move to [Django native choices](https://docs.djangoproject.com/en/3.0/ref/models/fields/#choices) or atleast [Enum](https://gist.github.com/treyhunner/fd2dc64efb50a147e0a29746862fe8fc).

**Comment by MaybeThisIsRu** [comment]
Can this issue be closed now?

https://github.com/dominno/django-moderation/commit/fbdf886a9839de98232a51de60f4457cd91b2ea9

**Comment by DmytroLitvinov** [comment]
Hi @MaybeThisIsRu ,
Yes, we can right now after a new release.
