### ISSUE TITLE
Drop support for unsupported Django versions

### ISSUE THREAD

**Issue by hirusi** [dominno/django-moderation#204]
Django 3.0 and earlier are no longer supported, except for 2.2 LTS, which support varying Python versions depending on the 2.2 patch version.

The setup.py and tox.ini file should be updated to reflect this.

We can drop all [1.11, 2.0, 2.1](https://github.com/dominno/django-moderation/blob/master/tox.ini#L8) from tox testing, and [update the next line to remove `3.0`](https://github.com/dominno/django-moderation/blob/master/tox.ini#L9).

**Comment by hirusi** [comment]
We'd also need to [drop their classifiers](https://github.com/dominno/django-moderation/blob/master/setup.py#L47-L49).

**Comment by hirusi** [comment]
It would be great to get this sorted before #202.

**Comment by DmytroLitvinov** [comment]
Hi @hirusi ,
We are open for PRs.
