### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by bitdivision** [dominno/django-moderation#207]
Would it be possible to make a release?

Currently django version is limited to 3.1. Would be great to have https://github.com/dominno/django-moderation/pull/206 in the released version.

**Comment by DmytroLitvinov** [comment]
You can install it via GitHub `master` branch for now, otherwise we need to ping @dominno for resolving that issue.

**Comment by bitdivision** [comment]
Thanks @DmytroLitvinov I'm currently installing from master, but obviously that's not ideal in production.

**Comment by DmytroLitvinov** [comment]
I know, but Dominik is the only person who can publish to PyPI.

**Comment by Scronullik** [comment]
I'm also really looking forward to a new release with support for the latest version of Django.

**Comment by shawnngtq** [comment]
follow

**Comment by carlosnasillo** [comment]
+1

**Comment by DmytroLitvinov** [comment]
Hi @dominno ,
As you see last release was at 2019 and right now 2022 - 3 years like we did not release our package but it has support for Django 3.2 :) 

I am ready to help you with maintaining the package at [PyPI](https://pypi.org/project/django-moderation/). My PiPY user - [DmytroLitvinov](https://pypi.org/user/DmytroLitvinov/). Let me know if you need some other help.

**Comment by dominno** [comment]
@DmytroLitvinov I added you, what else do you need ?

**Comment by DmytroLitvinov** [comment]
Thank you, @dominno .
Received and accepted the invitation. As for now seems like nothing.
Will try to release new version of package after reviewing one more time repo for supporting Django v3.2

**Comment by dominno** [comment]
no problem

**Comment by DmytroLitvinov** [comment]
Hi everyone,

I just started [new PR for releasing 0.8.0](https://github.com/dominno/django-moderation/pull/211). 
Welcome to review/comment/suggest.

**Comment by DmytroLitvinov** [comment]
Hi @dominno ,

Could you please also give me a maintainer at [ReadTheDocs](https://django-moderation.readthedocs.io/en/latest/) service so I can update documentation also?

**Comment by DmytroLitvinov** [comment]
Also,

Recently [released new version](https://github.com/dominno/django-moderation/releases/tag/v0.8.0) which supports Django>=2.2 :)

**Comment by dominno** [comment]
> Hi @dominno ,
> 
> Could you please also give me a maintainer at [ReadTheDocs](https://django-moderation.readthedocs.io/en/latest/) service so I can update documentation also?

I think you are added already, let know if it works

**Comment by DmytroLitvinov** [comment]
@dominno, thanks.
I have access to ReadTheDocs. Already updated build.
