### ISSUE TITLE
Support for Django 3.2+

### ISSUE THREAD

**Issue by ivanzugnoni** [dominno/django-moderation#210]
Hello everyone.

Any plans to add support for Django 3.2+? What are the main challenges to support it? Any guidance to contribute to the project in this direction? 2.2 is getting quite old now and becomes a deal breaker in most cases.

Thank you in advance.

**Comment by DmytroLitvinov** [comment]
Hi.

If you are willing to see Django 3.2 support here, you can create MR - this is an open-sourced project. Here is [contributing guide](https://django-moderation.readthedocs.io/en/latest/contributing.html).

**Comment by martinzugnoni** [comment]
Given that all tests are passing in `Django==3.2`, is it possible that the versions is already supported? Maybe it's simply not listed in the README file. Or is there any known issue about it?

```
$ pip3 freeze | grep Django
Django==3.2
```

```
$ python runtests.py
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..............................................................................................................................................
----------------------------------------------------------------------
Ran 142 tests in 1.939s

OK
Destroying test database for alias 'default'...
```

**Comment by DmytroLitvinov** [comment]
Hi @martinzugnoni ,

Yes, it is not mentioned in README file.
Currently, I just started to work on [release new 0.8.0 version](https://github.com/dominno/django-moderation/pull/211) with support for Django>=2.2.
Any comments/suggestions are welcome.

**Comment by DmytroLitvinov** [comment]
Hi guys,

Recently [released new version](https://github.com/dominno/django-moderation/releases/tag/v0.8.0) which supports Django>=2.2 :)
