### ISSUE TITLE
ManyToMany field support

### ISSUE THREAD

**Issue by caseycesari** [dominno/django-moderation#62]
I see that it is listed as known issue. Are there any plans to integrate support for ManyToMany fields? Or do you have any thoughts or know what the issues are for implementing support? I could take a shot at it if you have any experimental code/ideas. Thanks.

**Comment by iraycd** [comment]
@dominno Near future. It has been 4 years. 😄

**Comment by Allan-Nava** [comment]
Yes when is possibile to manage m2m?

**Comment by int-ua** [comment]
It's possible with custom Widgets. It may be hard, but possible.

**Comment by Allan-Nava** [comment]
Ok, thanks @int-ua 

Can you help me?
I have this problem when I add in setup.py  in INSTALLED_APPS = ["moderation"]

`
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

**Comment by DmytroLitvinov** [comment]
Closed because of inactivity.
